# Generated by Django 4.1.6 on 2023-02-05 16:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=100)),
                ('pub_date', models.CharField(max_length=13)),
            ],
            managers=[
                ('news', django.db.models.manager.Manager()),
            ],
        ),
    ]
